const SET_DATE_FILTER = "SET_DATE_FILTER";

const LOCATION_ACTION = {
  LOCATION_LIST_SUCCESS: "LOCATION_LIST_SUCCESS",
  ADD_LOCATION_SUCCESS: "ADD_LOCATION_SUCCESS",
  EDITL_LOCATION_SUCCESS: "EDITL_LOCATION_SUCCESS",
  DELETE_LOCATION_SUCCESS: "DELETE_LOCATION_SUCCESS"
};

const ROOM_ACTION = {
  ROOM_LIST_SUCCESS: "ROOM_LIST_SUCCESS",
  UPDATE_ROOM_SUCCESS: "UPDATE_ROOM_SUCCESS",
  DELETE_ROOM_SUCCESS: "DELETE_ROOM_SUCCESS",
  ADD_ROOM_SUCCESS: "ADD_ROOM_SUCCESS"
};

const USER_ACTION = {
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USERS_REGISTER_FAILURE",
  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",
  LOGOUT: "USERS_LOGOUT"
};

export {SET_DATE_FILTER, LOCATION_ACTION, ROOM_ACTION , USER_ACTION};
